#################### default parameters ################################
logo = "images/logo.png"
logo_width = "400px"
# Meta data
description = "Prometheus Science - Open Science for everyone"
author = "Andre M Chagas"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Get Started"
link = "contact"

  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/Prometheus_sci"

#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"